spring:

    datasource:
            url: jdbc:mariadb://localhost:3306/Farshock
            username: root
            password: toor
            driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop

        properties:
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
